export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_CREDENTIAL: 'INVALID_CREDENTIAL',
  SERVER_ERROR: 'SERVER_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_JWT: 'INVALID_JWT',
  NOT_FOUND: 'NOT_FOUND',
  DUPLICATE: 'DUPLICATE',
  REQUIRED_FIELD: 'REQUIRED_FIELD',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  NO_FIELDS_PROVIDED: 'NO_FIELDS_PROVIDED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
};
